### PR TITLE
Deterministic zip/tar

### LINKED ISSUE #342: Deterministic ZIP instead of Setup
The current develop branch delivers deterministic builds. I checked this also with removing node_modules and reinstalling them with yarn. The setup files on the other hand are not deterministic. We could instead ship a [deterministic zip](https://github.com/bitgenics/deterministic-zip). This would have the same Checksum every time.

### PR DESCRIPTION
**Pull request by faboweb**
Closes #342

### CODE REVIEW

**Comment by jolesbi** [comment]
what’s our strategy for releasing / verifying hashes? is that something we should or should not document somewhere?

**Comment by faboweb** [comment]
I output the MD5 hashsum. We could post this one in the channel to check determinism and also put it on the release page.

image

**Comment by mappum** [comment]
Nice work Fabo! I switched the hash function from MD5 to SHA256 (MD5 can be brute forced in a matter of seconds now!).

Although I'm having problems running the app after extracting it from the zip, seems like the deterministic zip may have messed up some file permissions. It runs fine before the zipping step.

**Comment by faboweb** [comment]
Thx for the test! Could you maybe assist me on this. I will test on Ubuntu. It runs fine on Windows.

**Comment by faboweb** [comment]
:/ It actually neither works on Ubuntu.

**Comment by mappum** [comment]
I looked into it and `zip` doesn't contain some file metadata that is useful for unix filesystems (permissions, etc.). Maybe for Mac and Linux we can just use `.tar.gz` since it preserves that info and we can still make it deterministic: https://github.com/dominictarr/deterministic-tar (at least the .tar part, hopefully we can make the .gz part deterministic).

**Comment by faboweb** [comment]
Sounds great. I experimented with another zipping lib which also didn't work on linux (checkout latest commit). I am down for `.tar.gz` do you want to take car of that? If you have to much to do. I continue on that tomorrow. (E2E tests might suffer but this has higher prio)

**Comment by faboweb** [comment]
`.tar.gz` results in the same behaviour

**Comment by faboweb** [comment]
found it: it is missing executable permissions. will try to leave those in.

**Pull request merged**
