### PR TITLE
Fabo/160 fix send page

### LINKED ISSUE #160: Send page is not visible
If you have atoms, the send page is not working.

image

### PR DESCRIPTION
**Pull request by faboweb**
fixes #160 

sneaked in a fix for #162

### CODE REVIEW

**Comment by ebuchman** [comment]
Cool this worked for me

**Comment by ebuchman** [comment]
Ah but the delegate tab is empty on this branch

**Comment by nylira** [comment]
Confirming that the Delegate page fails to work for here too.

**Comment by faboweb** [comment]
I can't confirm this on my environment.

image

Can you send me the errors appearing in your console?

**Pull request merged**
