### PR TITLE
Peng/389 release 0.4

### LINKED ISSUE #389: release 0.4.0
- [ ] make sure build for linux works
- [ ] make sure build for macos works
- [ ] make sure build for windows works
- [x] update version to 0.4.0

### PR DESCRIPTION
**Pull request by nylira**
* Resolves symlinks not being included in `tar.gz` by using `tar-fs` instead of `tar-stream`
* Updates version to 0.4.0
* Created Gaia binaries: download them from the pinned files on the #dev-gaia channel or build them yourself.

**Please follow [the release docs](https://github.com/cosmos/cosmos-ui/blob/peng/389-release-0-4/docs/release.md) and confirm these hashes for me: WIP**

Closes #389

### CODE REVIEW

**Comment by nylira** [comment]
I'm getting this error in the production build of Cosmos UI 0.4.0:

screen shot 2018-01-31 at 1 31 12 pm

I managed to find the error by adding `mainWindow.webContents.openDevTools()` in `app/src/main.index.js` after `mainWindow = new BrowserWindow...`

**Comment by nylira** [comment]
After creating an account or signing into an account with the 0.4.0 binary, the app refuses to set `config.modals.session.active` to `false`

screen shot 2018-01-31 at 2 23 48 pm
screen shot 2018-01-31 at 2 23 41 pm

**Comment by nylira** [comment]
So to summarize, using `tar-fs` creates a perfect tarball of the macOS binary:

screen shot 2018-01-31 at 3 00 17 pm

But `deterministic-tar` is stripping out the symlinks (among other things?), which is causing necessary files to be removed from the gzipped tarball, and `Cosmos.app` can no longer be opened.

You can confirm this by seeing that `Cosmos.app` runs after commenting out this line: https://github.com/cosmos/cosmos-ui/blob/178b4cfd425586268023e1025f2af27b2c1af097/tasks/release.js#L151

**Comment by faboweb** [comment]
I am very sorry. There was a commit missing in the deterministic-zip PR. The important part was, that the packed executable didn't have the rights to execute. I readded this.
As `tar-fs` caused issues in the combination with my code I removed it again in favor of `tar-stream`. I tested it on Ubuntu and it works. If the symlink problem still exists, I offer to patch this approach together with `tar-fs`.

**Comment by faboweb** [comment]
On devtools: You can set `COSMOS_DEVTOOLS=true`. Then even the production build will show the devtools.

**Comment by faboweb** [comment]
My Linux-build SHA256: 757dab38d271cb2fcaa516052d76e530bea80c872f22061889135bcdc67ccd5d

**Comment by nylira** [comment]
@faboweb thanks! I have an error related to `fs-stream` and symlinks when I try to build on macOS though, which is the reason why I tried out `tar-fs` earlier. `fs.readSync` is trying to read a symlink folder which seems to cause the error:

```
yarn build:darwin --binary=$GOPATH/src/github.com/cosmos/gaia/gaia-mac
```
```
Zipping files...

fs.js:693
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:693:18)
    at tryReadSync (fs.js:557:20)
    at Object.fs.readFileSync (fs.js:600:19)
    at files.filter.forEach.file (/Users/pz/Projects/cosmos-ui/tasks/release.js:159:63)
    at Array.forEach (<anonymous>)
    at glob (/Users/pz/Projects/cosmos-ui/tasks/release.js:158:10)
    at f (/Users/pz/Projects/cosmos-ui/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:160:13)
    at Glob._finish (/Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:197:8)
    at done (/Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:637:12)
    at /Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:626:10
    at RES (/Users/pz/Projects/cosmos-ui/node_modules/inflight/inflight.js:31:16)
    at f (/Users/pz/Projects/cosmos-ui/node_modules/once/once.js:25:25)
    at lstatcb_ (/Users/pz/Projects/cosmos-ui/node_modules/glob/glob.js:519:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by faboweb** [comment]
Sadly tar-fs doesn't produce deterministic builds.
The error seams to be in fs.readFileSync (line 159) can't read a folder. Those get filtered out but apparently symlinked folders are not detected correctly. I added a try catch to prevent the build from failing on these (https://github.com/cosmos/cosmos-ui/pull/422/commits/67642793f08045972dfac29eeaab4ea31342de1c). Would this work for you?

**Comment by nylira** [comment]
@faboweb It looks like the macOS build works with your warning bypassing the error. One minor issue is that using `tar-stream` is ballooning the size of `Cosmos.app` from 146MB to 339MB (by including symlink files or something?). But we can release with this and resolve it later.

**Comment by nylira** [comment]
Cosmos-darwin-x64_0.4.0.tar.gz
> SHA256: daf0099289b0b88898e66098f689ffcd204bf048b6da4413d341f075e073af77

Cosmos-linux-x64_0.4.0.tar.gz
> SHA256: 71e44df3518afa85710ef2851eb28459c15a36892a0ea05043b9243487ed9f89

Cosmos-win32-x64_0.4.0.zip
> SHA256: f0684a73a0d34e0c39d196adcfe9027e0e484cbed78b2b9aab4a8efd05068e4a

**Comment by faboweb** [comment]
Sadly the checksums are not equal :(

Cosmos-darwin-x64_0.4.0.tar.gz
> SHA256: ff27a1d063a7b303f8836bd6a9797a67aa4e4cceb4dac1e5bff9b836418ce150

Cosmos-linux-x64_0.4.0.tar.gz
> SHA256: b7314eadec7c55ec7687e799b4f9fc1cc30ad1391b1e82458cd7fa48b4770902

Cosmos-win32-x64_0.4.0.zip 
> SHA256: 19bf82b3b1cf3c88ff909c1781b913026d07220f196ba95a46a987d56bbd9b21

Regarding `tar-fs`: ok let's work on this when we have solved this issue.

**Comment by faboweb** [comment]
I created a follow up issue here: https://github.com/cosmos/cosmos-ui/issues/424

**Comment by mappum** [comment]
Got the same hashes as Peng when building with his `gaia` binaries :+1: (Although different for Windows, still something non-deterministic there).

Veriability isn't a blocker for this release though, we'll just have to get it working before launch.

**Pull request merged**
