### PR TITLE
Jordan/344 block explorer

### LINKED ISSUE #344: implement block explorer main page
- [x] search for block / transaction ID
- [x] show most recent 20 blocks
- [x] ~meta info about blocks in last day, hour, min etc...~ #381 

relates to #29

### PR DESCRIPTION
**Pull request by jolesbi**
- could use some advice on how to set up search for all blocks instead of just blocks since subscribing to tendermint event for `NewBlock`...

- not sure if the meta info from #344 is available? does anyone know?

- working on tests now

closes #344

### CODE REVIEW

**Comment by nylira** [comment]
The meta info isn't available. If we want it (which would be pretty cool to have), I think we have to store the data locally in a file or a database and then query that for the historical info. Of course we won't have data for when the UI is closed, but I think it's an acceptable compromise for a client-only block explorer -- like the Activity Monitor or Task Manager.

**Comment by faboweb** [comment]
I think tracking this while the app is open could be enough. I want to mention my concerns for introducing additional complexity by adding a database.

**Comment by jolesbi** [comment]
ok. i think we should merge this then. 

- there is already a separate ticket for tests #121 
- meta info would be cool but we need to discuss a strategy for this
- http://explorer.cosmosvalidators.com/#/ ???

**Comment by faboweb** [comment]
We aligned on including tests for all changed or created components per PR. ;P (sorry for being annoying)
Moving meta info out is ok. Could you maybe create a ticket for that?

**Comment by nylira** [comment]
I'll help with block search right now.

**Comment by nylira** [comment]
Not sure why this test is failing:

```
 FAIL  test/unit/specs/components/monitor/PageBlocks.spec.js
  ● PageBlocks › should show the search on click

    TypeError: Cannot read property 'filters' of undefined

      at BufferedConsole.Object.<anonymous>.console.error (test/unit/helpers/console_error_throw.js:10:9)
      at logError (node_modules/vue/dist/vue.runtime.common.js:1715:13)
      at globalHandleError (node_modules/vue/dist/vue.runtime.common.js:1703:7)
      at handleError (node_modules/vue/dist/vue.runtime.common.js:1695:3)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.js:4474:7)
      at VueComponent.update (node_modules/vue-test-utils/dist/vue-test-utils.js:1226:21)
      at node_modules/vue-test-utils/dist/vue-test-utils.js:1227:59
          at Array.forEach (<anonymous>)
      at VueComponent.update (node_modules/vue-test-utils/dist/vue-test-utils.js:1227:18)
      at node_modules/vue-test-utils/dist/vue-test-utils.js:1227:59
          at Array.forEach (<anonymous>)
      at VueComponent.update (node_modules/vue-test-utils/dist/vue-test-utils.js:1227:18)
      at Wrapper.trigger (node_modules/vue-test-utils/dist/vue-test-utils.js:1220:8)
      at Object.<anonymous> (test/unit/specs/components/monitor/PageBlocks.spec.js:24:36)
          at new Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)


Test Suites: 1 failed, 65 passed, 66 total
Tests:       1 failed, 3 skipped, 348 passed, 352 total
Snapshots:   85 passed, 85 total
Time:        9.344s
```

**Pull request merged**
