### PR TITLE
NiSession modal improvements

### LINKED ISSUE #172: Welcome Screen Passwords
All key generation methods rely on a password provided. There is no password field yet.

### PR DESCRIPTION
**Pull request by nylira**
* improves the visual design of the session modals (welcome, sign in, sign up, etc)
* splits the sign in with password into two different options:
  * restore account from seed
  * sign in with password
* created the password sign in field
* autofocus the seed and password fields on the respective pages so the user is saved a click
* the help icon in the top left of these modals now works

Fixes #172 

## Old

screen shot 2017-12-06 at 2 24 26 pm

## New

screen shot 2017-12-06 at 2 30 45 pm
screen shot 2017-12-06 at 2 30 48 pm
screen shot 2017-12-06 at 2 30 51 pm

@faboweb there's more to do of course:

* add password creation field to sign up
* add password creation to restore account
* add password entry to hardware

But I think this PR will be a net benefit for the release

### CODE REVIEW

**Comment by faboweb** [comment]
Are there tests for NiSessionRestore.vue and NILiSession.vue?

**Comment by jolesbi** [comment]
are we using passwords? this never came up in the wireframing exercise...

**Comment by faboweb** [comment]
All keys stored locally are mandatory password protected. Until this password was always "1234567890".

**Comment by nylira** [comment]
@faboweb passing tests have been added for those two components!

**Pull request merged**
