### PR TITLE
fix refresh button location + design

### LINKED ISSUE #72: Refresh Balance Design
The refresh button on the balance page was implemented, but there was no design applied.

### PR DESCRIPTION
**Pull request by nylira**
Fixes #72

### CODE REVIEW

**Comment by mappum** [comment]
It looks good, but I'm worried that the button being in the footer will make it not obvious enough. It's already not standard that we have a refresh button, so I have a feeling some people will be sitting there wondering why their incoming balance isn't showing up.

Maybe the solution is something like text under the balances that says "Last updated at <time>"? What are your thoughts @nylira @jolesbi ?

**Comment by nylira** [comment]
Yeah visibility is something I have to do. The plan is to move those footer buttons to the top of the screen for desktop

**Comment by mappum** [comment]
Ah perfect

**Comment by mappum** [comment]
Hm, not sure why the Circle tests froze.

**Pull request merged**
