### PR TITLE
Deterministic gaia binaries

### LINKED ISSUE #245: deterministic, verifiable builds
this is vert important. but can wait until next sprint.

JB:
> i'd like to hold off on implementing deterministic builds (with signed releases) until at least dec 28

Jae:
> as long as we don’t put blog posts out, and we put all the disclaimers, that sounds good.

related to #232 

@jaekwon

### PR DESCRIPTION
**Pull request by mappum**
Closes #245 

So far, I've only made the gaia binary builds deterministic. You'll now need to install [Docker](https://store.docker.com/search?type=edition&offering=community) to make production builds, but luckily its usage can be fully automated so we won't have to do anything special in the build process.

Will now have to investigate all the other sources of non-determinism in Electron app bundles and platform-specific packages.

### CODE REVIEW

**Comment by mappum** [comment]
Good news, I've investigated and our webpack output is deterministic, even after reinstalling the dependencies with `yarn` 👍 So now I'll just have to look into whatever is different inside the electron bundle output.

**Comment by mappum** [comment]
Known sources of non-determinism:

- [ ] Native module binaries - May be able to just get rid of all native deps so that we don't have to deal with them, (`keccak`, `leveldown`, `secp256k1`, `ed25519-supercop`)
- [ ] Release packages (e.g. `.dmg`, Windows installers, etc.)

**Comment by faboweb** [comment]
I like the idea of getting rid of the native binaries. But is this possible?

**Comment by mappum** [comment]
>I like the idea of getting rid of the native binaries. But is this possible?
  
Yes, should be easy in the short-term since we actually aren't using a lot of these deps right now 🤦‍♂️. We'll have to use them eventually for deriving fundraiser seeds, but we can deal with that before launch.

**Comment by mappum** [comment]
I was thinkign we'd have all the deteminism changes in this PR, but now it makes more sense to merge this as-is to get deterministic go binaries (and also a more convenient go compiler script for the build step). Then we can figure out determinism on the next layer (the `electron-builder` layer, #329) and merge that separately.

Will also have to remove the native module dependencies outside of this PR, which goes along with #315.

**Comment by nylira** [comment]
Yeah let's keep the PR smaller and merge what we have. Good work @mappum!

**Pull request merged**
